-- Criar tabela de estoque
create table public.estoque (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  nome text not null,
  quantidade integer not null,
  descricao text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar Row Level Security (RLS)
alter table public.estoque enable row level security;

-- Politica de LEITURA (SELECT): Usuário lê apenas seus próprios itens
create policy "Usuários podem ver apenas seu próprio estoque"
on public.estoque for select
using (auth.uid() = user_id);

-- Politica de INSERÇÃO (INSERT): Usuário insere itens vinculados ao seu ID
create policy "Usuários podem inserir em seu próprio estoque"
on public.estoque for insert
with check (auth.uid() = user_id);

-- Politica de ATUALIZAÇÃO (UPDATE): Usuário atualiza apenas seus itens
create policy "Usuários podem atualizar seu próprio estoque"
on public.estoque for update
using (auth.uid() = user_id);

-- Politica de EXCLUSÃO (DELETE): Usuário deleta apenas seus itens
create policy "Usuários podem deletar seu próprio estoque"
on public.estoque for delete
using (auth.uid() = user_id);